### ISSUE TITLE
Swagger error in Admin interface

### ISSUE THREAD

**Issue by petzlux** [opendatateam/cookiecutter-udata-theme#2]
The admin interface doesnt work properly for site administrator. The menu entries for the site admin dont show up.

````
udata_1          | 127.0.0.1 - - [06/Jul/2017 13:05:04] "GET / HTTP/1.1" 302 -
udata_1          | 172.22.0.1 - - [06/Jul/2017 13:05:05] "GET /en/admin/site HTTP/1.1" 200 -
udata_1          | 172.22.0.1 - - [06/Jul/2017 13:05:05] "GET /static/common.css?_=1499346305.43 HTTP/1.1" 200 -
udata_1          | 172.22.0.1 - - [06/Jul/2017 13:05:05] "GET /static/common.js?_=1499346305.43 HTTP/1.1" 200 -
udata_1          | 172.22.0.1 - - [06/Jul/2017 13:05:05] "GET /static/admin.css?_=1499346305.43 HTTP/1.1" 200 -
udata_1          | 172.22.0.1 - - [06/Jul/2017 13:05:05] "GET /static/admin.js?_=1499346305.43 HTTP/1.1" 200 -
udata_1          | 172.22.0.1 - - [06/Jul/2017 13:05:05] "GET /_themes/gouvlu/admin.css?_=1499346305.43 HTTP/1.1" 200 -
udata_1          | ERROR: Exception on /api/1/swagger.json [GET]
udata_1          |   | Traceback (most recent call last):
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
udata_1          |   |     rv = self.dispatch_request()
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
udata_1          |   |     return self.view_functions[rule.endpoint](**req.view_args)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/cors.py", line 38, in wrapped_function
udata_1          |   |     resp = make_response(f(*args, **kwargs))
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/udata/api/__init__.py", line 118, in wrapper
udata_1          |   |     return func(*args, **kwargs)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 313, in wrapper
udata_1          |   |     resp = resource(*args, **kwargs)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
udata_1          |   |     return self.dispatch_request(*args, **kwargs)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
udata_1          |   |     resp = meth(*args, **kwargs)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 771, in get
udata_1          |   |     return self.api.__schema__
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 73, in __get__
udata_1          |   |     value = self.func(obj)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 472, in __schema__
udata_1          |   |     self._schema = Swagger(self).as_dict()
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 179, in as_dict
udata_1          |   |     'definitions': self.serialize_definitions() or None,
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 420, in serialize_definitions
udata_1          |   |     for name, model in iteritems(self._registered_models)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/swagger.py", line 420, in <genexpr>
udata_1          |   |     for name, model in iteritems(self._registered_models)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/model.py", line 71, in __schema__
udata_1          |   |     schema = self._schema
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/model.py", line 144, in _schema
udata_1          |   |     properties[name] = field.__schema__
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 73, in __get__
udata_1          |   |     value = self.func(obj)
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/fields.py", line 170, in __schema__
udata_1          |   |     return not_none(self.schema())
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/fields.py", line 374, in schema
udata_1          |   |     enum = self._v('enum')
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/flask_restplus/fields.py", line 166, in _v
udata_1          |   |     return value() if callable(value) else value
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/udata/harvest/api.py", line 23, in backends_ids
udata_1          |   |     return [b.name for b in actions.list_backends()]
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/udata/harvest/actions.py", line 30, in list_backends
udata_1          |   |     return backends.get_all().values()
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/udata/harvest/backends/__init__.py", line 14, in get_all
udata_1          |   |     _ep_to_kv(e) for e in pkg_resources.iter_entry_points('udata.harvesters')
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/udata/harvest/backends/__init__.py", line 14, in <genexpr>
udata_1          |   |     _ep_to_kv(e) for e in pkg_resources.iter_entry_points('udata.harvesters')
udata_1          |   |   File "/usr/local/lib/python2.7/dist-packages/udata/harvest/backends/__init__.py", line 24, in _ep_to_kv
udata_1          |   |     cls = entrypoint.load()
udata_1          |   |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2188, in load
udata_1          |   |     self.require(env, installer)
udata_1          |   |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2202, in require
udata_1          |   |     items = working_set.resolve(reqs, env, installer)
udata_1          |   |   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
udata_1          |   |     raise VersionConflict(dist, req)
udata_1          |   | VersionConflict: (setuptools 5.5.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=18.5'))
udata_1          | 172.22.0.1 - - [06/Jul/2017 13:05:06] "GET /api/1/swagger.json?lang=en&_=1499346305700 HTTP/1.1" 500 -
udata_1          | 127.0.0.1 - - [06/Jul/2017 13:05:09] "GET / HTTP/1.1" 302 -
````

**Comment by petzlux** [comment]
I resolved this by making sure to have the latest version of setuptools installed.

`pip install --upgrade setuptools`

Should this be fixed in https://github.com/opendatateam/udata-dockers/blob/master/system/Dockerfile ?

**Comment by noirbizarre** [comment]
OK, I fixed it here: https://github.com/opendatateam/udata-dockers/blob/master/system/Dockerfile#L41
